// oxlint-disable no-template-curly-in-string
export const STOCK_PID_HELPERS =
  'var ri=(t)=>{try{return process.kill(t,0),!0}catch(r){return(typeof r==="object"&&r!==null&&"code"in r?String(r.code):void 0)==="EPERM"}},ii=(t)=>{if(!("pid"in t))return null;let r=t.pid;if(typeof r!=="number"||r<=0)return null;return r};';

export const STOCK_HUB_HEADER =
  'class Ft{logger;catalog;clientInfo;getOAuthDriver;onAuthFlowCompleted;onToolsListChanged;onToolCallAuthFailure;systemMcpConfigs=G();userMcpConfigs=G();servers=G();pendingConnections=new Map;seeds=new Map;storedDigests=new Map;availableResources=G();invalidToolsFingerprints=new Map;toolsListCache=new Map;toolsListChangeRefreshes=new Map;toolsListChangePendingRefreshes=new Set;cwd;shuttingDown=!1;clientNotifiers={};clientResourceSubscriptions=G();constructor({systemMcpConfigs:t={},userMcpConfigs:r={},logger:s,clientInfo:o,getOAuthDriver:l,onAuthFlowCompleted:u,onToolsListChanged:p,onToolCallAuthFailure:f,cwd:m,catalog:z}){this.systemMcpConfigs=ur(t),this.userMcpConfigs=ur(r),this.logger=s,this.catalog=z,this.clientInfo=o,this.getOAuthDriver=l,this.onAuthFlowCompleted=u,this.onToolsListChanged=p,this.onToolCallAuthFailure=f,this.cwd=m}';

export const STOCK_HUB_METHODS = {
  openPendingConnection:
    'openPendingConnection(t){let r=this.pendingConnections.get(t);if(!r)r=Promise.withResolvers(),r.promise.catch(()=>{}),this.pendingConnections.set(t,r);return r}',
  addServer:
    'async addServer(t,r){let m=this.openPendingConnection(t);try{await this.connectServer(t,r),m.resolve()}catch(O){if(!this.shuttingDown)this.discardCatalog(t,r);throw m.reject(O),O}finally{if(this.seeds.delete(t),this.pendingConnections.get(t)===m)this.pendingConnections.delete(t)}}',
  connectServer:
    'async connectServer(t,r){let s=performance.now(),o=r.type==="http"||r.type==="sse"?"remote":"stdio";if(this.shuttingDown)throw new a("MCP hub is shut down",{name:t});let l="success",u;try{let p=this.servers[t];if(p){let A=Object.keys(this.availableResources[t]??{}),y=Object.keys(this.clientResourceSubscriptions[t]??{});this.logger?.warn(`Server "${t}" already exists in hub state; removing stale entry before re-adding`,{name:t,transportPid:ii(p.transport),type:p.config.type,trackedResourceCount:A.length,trackedSubscriptionCount:y.length});try{await this.removeServer(t)}catch(O){this.logger?.warn(`Error removing stale server "${t}" (proceeding with add)`,{error:O,name:t,remainingServerEntry:Boolean(this.servers[t])})}}let f,m;if(r.type!=="http"&&r.type!=="sse"){let A=Ut({serverName:t,values:r.env}),y=gi({...process.env,...A??{}}),O=y?Object.fromEntries(Object.entries(y||{}).filter(([,b])=>b!==void 0).map(([b,I])=>[b,String(I)])):void 0,v=await Yr({name:t,command:r.command,args:r.args??[],env:O,configuredEnvKeys:Object.keys(A??{})});({client:f,transport:m}=await ti({serverArgs:{...v,...this.cwd?{cwd:this.cwd}:{},serverIdentity:Iy(r),connectTimeoutMs:r.connectTimeout},logger:this.logger?.child({name:t}),clientInfo:this.clientInfo}))}else{te({serverName:t,url:r.url,phase:`${r.type} transport startup`});let A=this.getOAuthDriver?.(t,r);this.logger?.info("OAuth driver check",{name:t,hasOAuthDriver:!!A,enableInteractiveAuth:A?.enableInteractiveAuth??!1}),{client:f,transport:m}=await Zr({serverArgs:{name:t,url:r.url,serverIdentity:Iy(r),headers:Ut({serverName:t,values:r.headers}),connectTimeoutMs:r.connectTimeout},transportKind:r.type==="sse"?"sse":"streamable-http",logger:this.logger?.child({name:t}),oauthDriver:A,clientInfo:this.clientInfo,onAuthFlowCompleted:(y)=>{this.onAuthFlowCompleted?.({serverName:t,...y})}})}if(this.servers[t]={name:t,config:r,client:f,transport:m},this.shuttingDown){try{await this.removeServer(t)}catch(A){this.logger?.warn("Error closing MCP server",{error:A,server:t})}throw new a("MCP hub shut down while the server was starting",{name:t})}let g=f.getServerVersion();this.logger?.info("MCP server connected",{name:t,...je(r),protocolVersion:vn(m),version:g?.version,serverImplementation:g?.name}),this.availableResources[t]=G(),f.setNotificationHandler(z5,async(A)=>{this.logger?.info("Received ResourceUpdatedNotification from MCP server",{notification:A,server:t}),await this.handleResourceUpdate(t,A.params.uri)}),f.setNotificationHandler(Py,async(A)=>{this.logger?.info("Received ResourceListChanged from MCP server",{notification:A,server:t}),await this.handleResourceListChanged(t,A.params?._meta?.assemblySessionId)}),f.setNotificationHandler(vy,async()=>{this.logger?.info("Received ToolListChanged from MCP server",{server:t}),await this.handleToolsListChanged(t)})}catch(p){throw l="error",u=Sn(p),p}finally{S.addToCounter("mcp_server_start_latency_ms",performance.now()-s,{outcome:l,type:o,serverName:t,reason:u})}}',
  handleToolsListChanged:
    'async handleToolsListChanged(t){this.toolsListCache.delete(t);let r=this.toolsListChangeRefreshes.get(t);if(r)return this.toolsListChangePendingRefreshes.add(t),await r;let o=(async()=>{do this.toolsListChangePendingRefreshes.delete(t),await this.onToolsListChanged?.(t);while(this.toolsListChangePendingRefreshes.has(t))})().finally(()=>{if(this.toolsListChangePendingRefreshes.delete(t),this.toolsListChangeRefreshes.get(t)===o)this.toolsListChangeRefreshes.delete(t)});return this.toolsListChangeRefreshes.set(t,o),await o}',
  removeServer:
    'async removeServer(t){if(!this.servers[t])throw new a("Server does not exist",{name:t});let s=this.servers[t].transport,o=ii(s),l=[],u;try{if(s&&typeof s.close==="function"){try{await s.close(),this.logger?.info(`Successfully stopped MCP server: ${t}`)}catch(f){l.push(f)}if(o!==null){if(l.length>0||ri(o))await this.killServerProcessTree(o,t)}}else this.logger?.warn(`Cannot stop MCP server ${t}: transport not available or missing close method`)}catch(f){l.push(f)}finally{delete this.servers[t],delete this.availableResources[t],this.invalidToolsFingerprints.delete(t),this.toolsListCache.delete(t);try{let f=this.clientResourceSubscriptions[t];if(f)await Promise.all(Object.keys(f).flatMap((m)=>Array.from(f[m]).map((g)=>this.unsubscribeClientFromResource(g,t,m))))}catch(f){u=f,this.logger?.warn("Failed to cleanup MCP server state",{error:u,server:t})}}let p=u?[...l,u]:l;if(p.length>0)throw AggregateError(p,`Failed to remove MCP server: ${t}`)}',
  restartStdioServers:
    'async restartStdioServers(t){let r=t?.onServerSettled,s=async(l)=>{if(!r)return;try{await r(l)}catch(u){this.logger?.error("onServerSettled callback threw",{error:u,server:l.serverName,phase:l.phase})}},o=Object.entries(this.servers).filter(([,{config:l}])=>l.type!=="http"&&l.type!=="sse").map(([l])=>l);for(let l of o)try{await this.retryServer(l),await s({phase:"start",serverName:l,success:!0})}catch(u){this.logger?.warn("Error restarting stdio MCP server after sandbox change",{error:u,server:l}),await s({phase:"start",serverName:l,success:!1,error:u instanceof Error?u:Error(String(u))})}return o}',
  retryServer:
    'async retryServer(t){let r=this.userMcpConfigs[t]??this.systemMcpConfigs[t]??null;if(!r)throw new a("Server configuration not found",{name:t});if(this.servers[t])this.logger?.info(`Stopping MCP server for retry: ${t}`),await this.removeServer(t);this.logger?.info(`Restarting MCP server: ${t}`),await this.addServer(t,r)}',
  listToolsForServer:
    'async listToolsForServer(t,r){if(!this.servers[t]){let R=this.seeds.get(t);if(!R)throw new a("Server does not exist",{name:t});return{tools:this.applyToolConfig(t,R.tools,r),seeded:!0}}let s=this.toolsListCache.get(t);if(s?.state==="failed"&&Date.now()>=s.retryAt)this.toolsListCache.delete(t),s=void 0;if(!s){let{config:R}=this.servers[t],u={state:"loading",promise:this.requestToolsList(t)};this.toolsListCache.set(t,u),u.promise.then((p)=>{if(this.toolsListCache.get(t)===u)this.toolsListCache.set(t,{state:"ready",tools:p}),this.persistCatalog(t,R,p)},(p)=>{if(this.toolsListCache.get(t)===u)this.toolsListCache.set(t,{state:"failed",error:p,retryAt:Date.now()+cee}),this.discardCatalog(t,R)}),s=u}let o;switch(s.state){case"loading":o=await s.promise;break;case"ready":o=s.tools;break;case"failed":throw s.error;default:return ut(s)}return{tools:this.applyToolConfig(t,o,r),seeded:!1}}',
  requestToolsList:
    'async requestToolsList(t){let r=Date.now()+Dt(),s=()=>Math.max(1,r-Date.now()),o;try{o=await this.servers[t].client.listTools(void 0,{timeout:s()})}catch(l){if(hn(l))this.logger?.warn("MCP server returned a tool with an unresolvable $ref; listing tools without output-schema cache",{server:t,error:l.message}),o=await this.listToolsSkippingInvalid(t,s());else if(dn(l))o=await this.listToolsSkippingInvalid(t,s());else throw l}if(!o.tools)throw new a("Server did not return tools",{name:t});return o.tools}',
  listResourcesForServer:
    'async listResourcesForServer(t,r){if(!this.servers[t])throw new a("Server does not exist",{name:t});let s=await this.servers[t].client.listResources({_meta:{assemblySessionId:r}});if(!s.resources)throw new a("Server did not return resources",{name:t});let o=G();for(let l of s.resources)o[l.uri]=l;return this.availableResources[t]=o,s.resources}',
  listResourceTemplatesForServer:
    'async listResourceTemplatesForServer(t){if(!this.servers[t])throw new a("Server  does not exist",{name:t});let r=await this.servers[t].client.listResourceTemplates();if(!r.resourceTemplates)throw new a("Server  did not return resource templates",{name:t});return r.resourceTemplates}',
  readResource:
    'async readResource(t,r){if(!this.servers[t])throw new a("Server  does not exist",{name:t});let s=await this.servers[t].client.readResource({uri:r});if(!s.contents||s.contents.length===0)throw new a("Server did not return resource contents",{name:t});if(s.contents.length>1)throw new a("Server returned multiple resources:",{name:t,paths:s.contents.map((o)=>o.uri)});return s.contents[0]}',
  callTool:
    'async callTool(t,r,s,o="unknown-session",l="AGENT",u=void 0){let p=this.servers[t];if(!p){let A=this.pendingConnections.get(t);if(!A)throw new a("Server does not exist",{name:t});if(await QH(A.promise,u),p=this.servers[t],!p)throw new a("Server does not exist",{name:t})}let f=p.config.type==="http"||p.config.type==="sse",m;try{m=await p.client.callTool({name:r,arguments:s,_meta:{assemblySessionId:o,caller:l}},fo,{timeout:p.config.timeout??Tee,...u?{signal:u}:{}})}catch(A){if(f){let X=A instanceof Error?A.message:String(A);if(It(X))this.notifyToolCallAuthFailureInBackground(t);throw A}let z=ch(A,p.client.transport!==void 0);if(!z)throw A;throw new Br(t,r,z,A)}let g=fo.safeParse(m);if(!g.success)throw new a("Invalid CallToolResult",{name:t,errorMessage:JSON.stringify(g.error.issues)});if(f&&g.data.isError===!0&&g.data.content.some((A)=>A.type==="text"&&It(A.text)))this.notifyToolCallAuthFailureInBackground(t);return g.data}',
  subscribeToServerResource:
    'async subscribeToServerResource(t,r){let s=this.servers[t];if(!s)throw new a("Server does not exist",{name:t});await s.client.subscribeResource({uri:r})}',
  unsubscribeFromServerResource:
    'async unsubscribeFromServerResource(t,r){let s=this.servers[t];if(!s){this.logger?.warn(`Cannot unsubscribe: Server ${t} does not exist`);return}await s.client.unsubscribeResource({uri:r}),this.logger?.info(`Unsubscribed from resource ${r} on server ${t}`)}',
};

export const STOCK_HUB_MODULE = `${STOCK_PID_HELPERS}${STOCK_HUB_HEADER}${Object.values(STOCK_HUB_METHODS).join('')}}`;
